# 0. Description --------------------------------------------------------------
#
# Author: Ting-Chih Hung
#
# Last Modified: 2025-09-19
#
# Goal: Generate LaTeX tables from randomization inference results for paper
#
# Inputs:
# - outputs/tables/fisher_tests.csv
# - outputs/tables/fisher_tests_permuted_stats.csv
#
# Outputs:
# - papers/tables/randomization_results.tex
#

# 1. Load Libraries -----------------------------------------------------------

library(tidyverse)
library(kableExtra)

# 1.1 Helper Functions --------------------------------------------------------

# Function to generate LaTeX table with proper formatting
generate_latex_table <- function(data, filename, caption, label) {
  
  # Generate LaTeX table using kableExtra
  latex_table <- data |>
    kable(
      format = "latex",
      booktabs = TRUE,
      caption = caption,
      label = label,
      escape = FALSE,
      align = c("l", "r", "r", "r", "r")
    ) |>
    kable_styling(
      latex_options = c("hold_position"),
      position = "center",
      full_width = FALSE
    ) |>
    footnote(
      general = paste0(
        "P-values computed via randomization inference with 10000 Monte Carlo permutations. ",
        "*** $p < 0.001$, ** $p < 0.01$, * $p < 0.05$. ",
        "Test statistic is the variance-weighted difference in means."
      ),
      general_title = "Notes:",
      footnote_as_chunk = TRUE,
      escape = FALSE,
      threeparttable = TRUE
    )
  
  # Create directory if it doesn't exist
  dir.create(dirname(filename), recursive = TRUE, showWarnings = FALSE)
  
  # Write to file with header comment
  cat(
    "% This file is auto-generated by code/05_generate_latex_tables.R\n",
    "% Do not edit manually\n",
    "% Results from Fisher's exact randomization test\n",
    "% P-values computed via Monte Carlo with 10000 permutations\n",
    "% \n",
    "% Required LaTeX packages:\n",
    "% \\usepackage{booktabs}\n",
    "% \\usepackage{threeparttable}\n",
    "% \\usepackage{array}\n\n",
    file = filename
  )
  
  # Write the table to file
  cat(latex_table, file = filename, append = TRUE)
  
  return(invisible(filename))
}

# 2. Read Data ----------------------------------------------------------------

fisher_results <- read_csv(file.path("outputs", "tables", "fisher_tests.csv"))

# 3. Format Results for Publication ------------------------------------------

# Create a comprehensive table with key statistics
results_table <- fisher_results |>
  mutate(
    test_stat_fmt = sprintf("$%.4f$", statistic),
    p_value_fmt = case_when(
      p.value == 0 ~ paste0("< ", sprintf("$%.1e$", 1/10000)),
      p.value < 0.001 ~ sprintf("$%.4f$", p.value),
      TRUE ~ sprintf("$%.3f$", p.value)
    ),
    # Add significance stars
    significance = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.01 ~ "**", 
      p.value < 0.05 ~ "*",
      TRUE ~ ""
    ),
    # Combine p-value and significance
    p_with_sig = paste0(p_value_fmt, significance),
    p.value.se = sprintf("$%.3f$", p.value.se)
  ) |>
  select(year, test_stat_fmt, p_with_sig, p.value.se, n_permutations) |>
  rename(
    Year = year,
    `Test Statistic` = test_stat_fmt,
    `P-value` = p_with_sig,
    `P-value SE` = p.value.se,
    `Num. of Permutations` = n_permutations
  )

# 4. Generate LaTeX Table ----------------------------------------------------

# Generate the main results table
output_file <- file.path("outputs", "tables", "randomization_results.tex")

generate_latex_table(
  data = results_table,
  filename = output_file,
  caption = "Randomization Inference Results for Ballot Order Effects.",
  label = "randomization-results"
)

cat("\nLaTeX table generated successfully!\n")
cat("File created: outputs/tables/randomization_results.tex\n")
